# action.yml
name: 'Hugo blog publisher'
description: 'Publish the public folder of a Hugo build output.'
icon: "arrow-right-circle"
inputs:
  repo:  # id of input
    description: 'The repository to publish to.'
    required: true
    default: ''
  branch:  # id of input
    description: 'The branch to push to.'
    required: false
    default: 'main'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.branch }}
